name: Create and publish a package


on:
  push:

env:
  REGISTRY: ghrc.io
  IMAGE_NAME:

jobs:
  build-and-publish-image:
    run-on: ubuntu-latest
    permissions:
      contest: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - mame: Log in the container REGISTRY
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v.5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tag: ${{ steps.meta.ouptuts.tags }}
          labels: ${{ steps.meta.ouptuts.labels }}